name: Service-CI
on:
  push:
    branches:
    - 'main'
    - 'develop'
    - 'feature/**'
    - 'feat/**'
    - 'release/**'
    - 'releases/**'
    path-ignore:
    - 'migrations/**'

env:
  GO_VERSION: '1.20'
  HELM_VERSION: 'v3.13.3'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Vet source code
      run: |
        go vet ./...
    
    - name: Run unit tests
      run: |
        go test ./...
  
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

    - name: Run linter
      run: |
        ./bin/golangci-lint run

  validate-helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: ${{ env.HELM_VERSION }}

    - name: Lint Helm Chart
      run: |
        helm lint ./app

  containerize:
    runs-on: ubuntu-latest
    needs: [unit-tests, static-analysis]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
